[local]
localhost

[mongodb]
mongodb-dev.aravind381.online

[catalogue]
catalogue-dev.aravind381.online

[redis]
redis-dev.aravind381.online

[user]
user-dev.aravind381.online

[cart]
cart-dev.aravind381.online

[mysql]
mysql-dev.aravind381.online

[shipping]
shipping-dev.aravind381.online

[rabbitmq]
rabbitmq-dev.aravind381.online

[payment]
payment-dev.aravind381.online

[frontend]
frontend-dev.aravind381.online


